// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgyObg4SNJ2_r1nF3CAsTJsnKHVvxfcrs',
    appId: '1:247178888207:web:d526ab40c65c9007710f7a',
    messagingSenderId: '247178888207',
    projectId: 'fruit-hub-3da3e',
    authDomain: 'fruit-hub-3da3e.firebaseapp.com',
    storageBucket: 'fruit-hub-3da3e.firebasestorage.app',
    measurementId: 'G-D6GBDS4014',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGIZreBt2fVk4z5WD-0wOGzMuZfIHpFP8',
    appId: '1:247178888207:android:50f09665b81211ae710f7a',
    messagingSenderId: '247178888207',
    projectId: 'fruit-hub-3da3e',
    storageBucket: 'fruit-hub-3da3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVLZMgZSxbVuSEyQuSm-lc4YswUvykznc',
    appId: '1:247178888207:ios:5b78a62441166497710f7a',
    messagingSenderId: '247178888207',
    projectId: 'fruit-hub-3da3e',
    storageBucket: 'fruit-hub-3da3e.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVLZMgZSxbVuSEyQuSm-lc4YswUvykznc',
    appId: '1:247178888207:ios:5b78a62441166497710f7a',
    messagingSenderId: '247178888207',
    projectId: 'fruit-hub-3da3e',
    storageBucket: 'fruit-hub-3da3e.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgyObg4SNJ2_r1nF3CAsTJsnKHVvxfcrs',
    appId: '1:247178888207:web:8c0b539c1d8e52d7710f7a',
    messagingSenderId: '247178888207',
    projectId: 'fruit-hub-3da3e',
    authDomain: 'fruit-hub-3da3e.firebaseapp.com',
    storageBucket: 'fruit-hub-3da3e.firebasestorage.app',
    measurementId: 'G-G5G80TCGHS',
  );
}
